// Centralised icon exports — every name here is verified to exist in
// @hugeicons/core-free-icons so the build never breaks on a bad import.
export { HugeiconsIcon } from '@hugeicons/react'

export {
  DashboardSquare02Icon as DashboardIcon,
  UserGroupIcon as AdminsIcon,
  ShieldUserIcon as RolesIcon,
  SquareLockPasswordIcon as PermissionsIcon,
  Location04Icon as LocationsIcon,
  GlobalIcon as GlobeIcon,
  Note04Icon as AuditIcon,
  Analytics02Icon as AnalyticsIcon,
  ChartUpIcon as TrendUpIcon,
  UserSquareIcon as ProfileIcon,
  UserCircle02Icon as UserCircleIcon,
  Logout03Icon as LogoutIcon,
  SearchIcon,
  PlusSignIcon as AddIcon,
  Edit02Icon as EditIcon,
  Delete03Icon as DeleteIcon,
  Cancel02Icon as CloseIcon,
  CheckmarkCircle02Icon as CheckIcon,
  TickDouble02Icon as TickDoubleIcon,
  CheckmarkSquare02Icon as CheckSquareIcon,
  ArrowLeft02Icon as ArrowLeftIcon,
  ArrowRight02Icon as ArrowRightIcon,
  ArrowDown02Icon as ChevronDownIcon,
  ArrowUp02Icon as ChevronUpIcon,
  Menu02Icon as MenuIcon,
  Moon02Icon as MoonIcon,
  Notification03Icon,
  MailIcon,
  Mail02Icon,
  SentIcon,
  EyeIcon,
  ViewOffSlashIcon as EyeOffIcon,
  MoreVerticalIcon as MoreIcon,
  FilterHorizontalIcon as FilterIcon,
  Calendar05Icon as CalendarIcon,
  Building06Icon as BuildingIcon,
  InformationCircleIcon as InfoIcon,
  Settings03Icon as SettingsIcon,
  Refresh01Icon as RefreshIcon,
  SquareLockCheck02Icon as LockCheckIcon,
  UnfoldMoreIcon,
  CopyIcon,
  MapPinIcon,
  Location05Icon as PinIcon,
  Idea01Icon as IdeaIcon,
} from '@hugeicons/core-free-icons'
